= tarball-repo

== Introduce
If there are lots of servers you need to install java, maven, tomcat, etc, every download
from the origin website is very time-consuming, only one copy in a resource server in local
network is ideal.

The simple project use nginx, fcgiwrap, bash script to setup a simple website which hold
the tarballs for downloading.

== Installation
tarball-repo can be installed on any directory, the default configuration use `/var/website/tarball-repo`.
If use another directory, see details in website.conf and website.tarball-repo.subconf

 # apt-get install nginx
 # apt-get install fcgiwrap

 # mkdir -p /var/website
 # cd /var/website
 # git clone https://github.com/redmark/tarball-repo.git
 # ln -s `pwd`/tarball-repo/website.conf /etc/nginx/conf.d/
 # ln -s `pwd`/tarball-repo/website.tarball-repo.subconf/etc/nginx/conf.d/

download tarballs from their official website to downloads directory

== Client access url
detail usage see section cgi-bin/choose

 wget --content-disposition http://some.web.site/tarball-repo/cgi-bin/choose?java
 wget --content-disposition http://some.web.site/tarball-repo/cgi-bin/choose?maven=3.3.3
 wget --content-disposition http://some.web.site/tarball-repo/cgi-bin/choose?tomcat=8.5
 curl -L -J -O http://some.web.site/tarball-repo/cgi-bin/choose?tomcat=8.5

show all downloads  tarballs

 curl http://some.web.site/tarball-repo/downloads/


== Structure
 .
 ├── cgi-bin
 │   ├── choose
 │   ├── choose.d
 │   │   ├── jdk.sh
 │   │   ├── maven.sh
 │   │   └── tomcat.sh
 │   └─── conf.sh
 ├── downloads
 │   └── README.adoc
 ├── LICENSE
 ├── README.adoc
 ├── website.conf
 └── website.tarball-repo.subconf


=== cgi-bin/choose
It's the main executable bash script which will be executed when `/tarball-repo/cgi-bin/choose?_name_=_version_` is accessed by client.
It redirect to download url of the latest tarballs on the server.

* if no version ,the latest one will be used

 /tarball-repo/cgi-bin/choose?jdk                 the latest jdk
 /tarball-repo/cgi-bin/choose?maven               the latest maven
 /tarball-repo/cgi-bin/choose?tomcat              the latest tomcat

* with version

 /tarball-repo/cgi-bin/choose?maven=3.3.9         maven 3.3.9

* the version can be partial one, e.g.

 /tarball-repo/cgi-bin/choose?java=7              the latest jdk7, even if jdk8 is in the download directory

=== conf.sh
set some custom variable & function, see comments in the file

=== cgi-bin/latest.d/
directory contains the bash scripts sourced by latest bash script, role these bash scripts is to get the url for download

=== downloads/
contains the tarball downloaded from origin website. +
Content-Disposition header is added for zip tgz gz file.

=== website.conf & website.tarball-repo.subconf
nginx configuration frags, they stands for a virtual host named website, and a app named tarball-repo, see comments in it
